server: "https://cas.uni-mannheim.de/cas/login"
service: 'https://portal.uni-mannheim.de/qisserver/rds?state=user&type=1'
tor: 'https://portal.uni-mannheim.de/qisserver/rds?state=htmlbesch&moduleParameter=Student&menu_open=n&navigationPosition=pruefungen%2Cnotenspiegel&breadcrumb=notenspiegel&topitem=pruefungen&subitem=notenspiegel'
exam: 'https://portal.uni-mannheim.de/qisserver/rds?state=user&type=8&topitem=pruefungen&breadCrumbSource=portal'
login: 'https://cas.uni-mannheim.de/cas/login?service=https%3A%2F%2Fportal2.uni-mannheim.de/portal2/rds%3Fstate%3Duser%26type%3D1'
logout: 'https://portal.uni-mannheim.de/qisserver/rds?state=user&type=4&re=last&category=auth.logout&breadCrumbSource=portal'
portal: 'https://portal.uni-mannheim.de'
#user credentials
username: username
password: password